# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: uxms.matrix::lang.tables.page_title_one

# Model Form Field configuration
form: ~/plugins/uxms/matrix/models/table/fieldsfordatas.yaml

# Model Class name
modelClass: Uxms\Matrix\Models\Table

# Default redirect location
defaultRedirect: uxms/matrix/datas

# Update page
update:
    title: uxms.matrix::lang.datas.edit
