# ===================================
#  List Behavior Config
# ===================================

title: uxms.matrix::lang.tables.page_title
list: ~/plugins/uxms/matrix/models/table/columns.yaml
modelClass: Uxms\Matrix\Models\Table
recordUrl: uxms/matrix/datas/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 30
showSetup: true
showCheckboxes: true
defaultSort:
    column: created_at
    direction: asc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
